//Script to pull appropriate copy in to #main-copy
(function(){
var loc = window.location.href; //get url
if(/mil/.test(loc)) {
$("#main-copy").prepend("<h2>Utilize your military experience to advance your career.</h2><p>Florida State College at Jacksonville (FSCJ) has a longstanding history of supporting veterans, active military and their families. FSCJ’s <a href='http://www.fscj.edu/military-veterans/veterans-benefits/before-applying-for-va-educational-benefits/'>Military and Veterans Service Center</a> (MVSC) has helped more than 2,200 veterans take the next step in their education.</p><p>Our dedicated MVSC staff will help you navigate military tuition assistance and VA benefits, including the GI Bill.</p><p>Explore the many options and benefits for military and veterans available at FSCJ and then let us help you select the degree or certificate that best fits your objective.</p>");
}
else if(/hsya/.test(loc)) {
$("#main-copy").prepend("<h2>Turn your high school diploma into a degree at FSCJ.</h2><p>Taking the next step toward college is an exciting and important decision. Florida State College at Jacksonville (FSCJ) offers more than <span>150 program options</span> from which to choose, including the Associate in Arts/University Transfer degree. If you’re unsure about what it is you want to study, we encourage you to check out <a href='https://fscj.emsicareercoach.com/'>Career Coach</a>, our degree and career exploration tool that is designed to help you find your perfect career by providing the most current local data on wages, employment, job postings and associated education and training.</p><p>Ranked nationally as one of the <span>top 25 most affordable public, four-year institutions</span>, FSCJ offers a variety of financial assistance opportunities including scholarships, grants and federal aid to help you achieve your goals.</p><p>Explore the many options available at FSCJ and then let us help you select the degree or certificate that best fits your objective.</p>");
}
else if(/wkad/.test(loc)) {
$("#main-copy").prepend("<h2>Gain the skills you need for the career you want.</h2><p>Florida State College at Jacksonville (FSCJ) understands the <span>unique needs of the non-traditional student</span>. Whether you’re coming back to college to finish your degree, starting for the first time or looking for that credential to help advance your career, we offer the resources you need to reach your goals.</p><p>Take classes online at your convenience or on campus during the day, night and weekend. Campuses are easily <span>accessible</span> from anywhere in Northeast Florida and include child care facilities. We have <span>affordable</span> tuition with financial assistance available if needed. And, you can use prior learning, shorter class terms and accelerated curriculums to finish even faster.</p><p>Explore the many options available at FSCJ and then let us help you select the degree or certificate that best fits your objective.</p>");
}
else if(/fgen/.test(loc)) {
$("#main-copy").prepend("<h2>Start a family tradition...be the first to attend college.</h2><p>Florida State College at Jacksonville (FSCJ) has been rooted in the community for more than 50 years and is proud to serve students just like you who are the first in their families to attend college. We understand that <span>your experience is unique</span> and are prepared to help you succeed in your educational and career goals.</p><p>FSCJ offers more than <span>150 degree and certificate options</span> with affordable tuition and financial assistance if needed. If you’re uncertain about what it is you’d like to study, we encourage you to check out <a href='https://fscj.emsicareercoach.com/'>Career Coach</a>, our degree and career exploration tool that is designed to help you find a goodyour perfect career by providing the most current local data on wages, employment, job postings, and associated education and training.</p><p>Explore the many options available at FSCJ and then let us help you select the degree or certificate that best fits your objective.</p>");
}
else {
$("#main-copy").prepend('<h2>Take the Next Step. Open New Doors.</h2><p>Florida State College at Jacksonville (FSCJ) has been rooted in the community for more than 50 years and is proud to serve our diverse and unique population of students. With more than <span>150 degree and certificate programs</bold>, there’s something for everyone.</p><p>Whether you’re starting college for the first time, coming back to finish your degree or looking for that credential to help advance your career, we offer the <span>resources you need to reach your goals</span>. Conveniently located throughout Northeast Florida, FSCJ offers classes on campus during the day, night, on weekends or online for your convenience.</p><p>Explore the many options available at FSCJ and then let us help you select the degree or certificate that best fits your objective.</p>');
}
})();